robot_base_frame: base_link
footprint: [[0.35, 0.2], [0.35, -0.2], [-0.25, -0.2], [-0.25, 0.2]]
footprint_padding: 0.01

update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 10.0 # 0.5

obstacle_range: 2.5
raytrace_range: 3.0
resolution: 0.05

# Layers
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, sensor_frame: base_laser_front_link, topic: laserscan, marking: true, clearing: true}

inflation:
    inflation_radius: 0.05
