robot_base_frame: virtual_base
footprint: [[0.35, 0.2], [0.35, -0.2], [-0.25, -0.2], [-0.25, 0.2]]
footprint_padding: 0.01

update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.5

obstacle_range: 2.5
raytrace_range: 3.0
resolution: 0.05

# Layers
static_layer:
    map_topic: map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser
    laser: {data_type: LaserScan, sensor_frame: base_laser_front_link, topic: laserscan, marking: true, clearing: true}

inflation_layer:
    inflation_radius: 0.1
